### ISSUE TITLE
Formatter uses wrong symbol after locale fallback

### ISSUE THREAD

**Issue by Stormsabre** [bojanz/currency#12]
if using CAD currency for example, and i want to display the symbol for "en-CA", GetSymbol prioritizes "en" over "en-CA" so it will return "CAD$" and not "$"

**Comment by bojanz** [comment]
Hm, I don't see that.

Added:
```
		{"CAD", currency.NewLocale("en-CA"), "$", true},
```
to TestGetSymbol() and it is passing.

**Comment by Stormsabre** [comment]
You are right, its not an issue in GetSymbol, the issue is actually with the formatter and the currencyFormats data. There is no "en-CA" currencyformat in data.go so it instead takes en as its locale. Formatter passes "en" to GetSymbol instead of "en-CA" so it pulls the "CA$" symbol instead of "$".

**Comment by bojanz** [comment]
Good catch, thanks!

Pushed a fix.
