### ISSUE TITLE
NoSql Support

### ISSUE THREAD

**Issue by erotokritosVall** [bojanz/currency#15]
Are there any plans to support storing Amount in no-sql databases? (for example mongo)

If not do you have any tips on how to store that info? (mostly the number part concerns me)

**Comment by bojanz** [comment]
Mongo appears to have a decimal type you can use: https://www.mongodb.com/docs/manual/tutorial/model-monetary-data/#std-label-numeric-decimal

**Comment by erotokritosVall** [comment]
You are right, but I was wondering if there is built-in support for it

I solved the problem by storing the number as int64
I know it is not entirely correct but it will suffice for my use case

**Comment by bojanz** [comment]
Using an int64 is a fine workaround for most systems. Still, you should be able to do something like this when storing the amount:
```
d, err := primitive.ParseDecimal128(a.Number())
```
