### ISSUE TITLE
Introduce currency.ForCountryCode() for getting a country's currency

### ISSUE THREAD

**Issue by mboudraa** [bojanz/currency#23]
It would be very useful to expose a function like 
```go
fun currency.getCode(countryCode string) (string, error) 
```

it would allow to retrieve the currency used by default for a given country

**Comment by bojanz** [comment]
That does sound useful.

We have the data available in https://github.com/unicode-org/cldr-json/blob/main/cldr-json/cldr-core/supplemental/currencyData.json, we could parse it into a currencyCountries / countryCurrencies of type map[string][string] that maps country codes to currency codes.

**Comment by mboudraa** [comment]
Yes that would be great.
Also at the risk of being to demanding 😅, Having the ability to have the currency full name would be also extremely useful for building drop downs of available currencies for selection for example

**Comment by mboudraa** [comment]
> we could parse it into a currencyCountries / countryCurrencies of type map[string][string] that maps country codes to currency codes.

yes I build a local map of country to currency map[string]string that would allow me to do something like
```go
currencyCode := countryCurrency["CA"]
digits, err := currency.GetDigits(countryCode)
```

having to not maintain that map would be fantastic

**Comment by bojanz** [comment]
```
 Having the ability to have the currency full name would be also extremely useful for building drop downs of available currencies for selection for example
```
This is covered in the README:
```
Currency names are not included because they are rarely shown, but need significant space. Instead, they can be fetched on the frontend via [Intl.DisplayNames](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DisplayNames).
```
