### ISSUE TITLE
Add support for the accounting formatter style (negative amounts in parenthesis)

### ISSUE THREAD

**Issue by jarreds** [bojanz/currency#26]
Eg `($1.00) == -$1.00`

**Comment by bojanz** [comment]
What is the use case/context in which you would use the parenthesis format?

**Comment by jarreds** [comment]
We are using the library within a core ledger system, and we would like to use the standard accounting format to represent debit/credit balances:

<img width="688" alt="image" src="https://github.com/bojanz/currency/assets/1414175/22077c9a-2b05-4f73-8dab-45726497a262">

Becomes:

<img width="688" alt="image" src="https://github.com/bojanz/currency/assets/1414175/17f7685d-9d2b-469b-8a99-5d7822d5868c">

**Comment by bojanz** [comment]
That's a valid use case, and one worth supporting.

Implementation notes:
- We need to add an accountingPattern to the currencyFormat struct
- We need to parse the "accounting" pattern in readFormat() in gen.go
- We should omit the accounting pattern if it's the same as the standard one, and have the formatter know how to fallback.
- The Formatter needs a Style field which can be "standard" or "accounting" and which influences which pattern is picked by getPattern(). We want to introduce an enum type for the Style like we did for RoundingMode and Display, but currency.Style is not distinctive enough. Perhaps FormatterStyle?

We'll want to do the CLDR v44 update first, it looks like it has relevant fixes (for the accounting patterns in various locales, such as the ones inheriting from es-419)
