### ISSUE TITLE
Negative currency converted to `BigInt` becomes positive

### ISSUE THREAD

**Issue by kvikas** [bojanz/currency#27]
Hello I noticed that a negative amount when converted to `BigInt` results in a positive number. [Here is a working example](https://go.dev/play/p/fAaUj47TXIX).
```
package main

import (
	"fmt"
	"math/big"

	"github.com/bojanz/currency"
)

func main() {
	amount, _ := currency.NewAmount("-9.00", "USD")
	zero, _ := currency.NewAmount("0", "USD")
	isNegative, _ := amount.Cmp(zero)

	fmt.Printf("amount: %v\n", amount)
	fmt.Printf("amount < 0: %v\n", isNegative)

	bigInt := amount.BigInt()
	zeroBigInt := big.NewInt(0)

	fmt.Printf("bigInt : %v\n", bigInt)
	fmt.Printf("bigInt < 0 : %v\n", bigInt.Cmp(zeroBigInt))
}

amount: -9.00 USD
amount < 0: -1
bigInt: 900
bigInt < 0 : 1
```

Is this expected?

**Comment by bojanz** [comment]
Not expected and definitely a bug.

This is caused by apd.Decimal always storing the coefficient as positive, and maintaining a separate Negative boolean. We need to take that into account in amount.BigInt(), and multiply by -1 when needed.

**Comment by kvikas** [comment]
@bojanz do you want a PR?

**Comment by bojanz** [comment]
@kvikas PRs always welcome :) We should add a negative number to TestAmount_BigInt() as well.
