### ISSUE TITLE
Why does this code work? What is the purpose of Locale?

### ISSUE THREAD

**Issue by curiosport** [bojanz/currency#31]
I ran into the problem that I only have the country name and not the Locale, so reading the code among other things in the end I don't understand what is the purpose of Locale in this package?

Why if I do this don't I get any errors or an empty output?
`locale := currency.NewLocale(" ")`

```
package main

import (
	"fmt"

	"github.com/bojanz/currency"
)

func main() {
	locale := currency.NewLocale(" ")
	formatter := currency.NewFormatter(locale)
	amount, err := currency.NewAmount("1245.988", "JPY")

	fmt.Println(err, formatter.Format(amount))

	formatter.MaxDigits = 2
	fmt.Println(formatter.Format(amount))

	formatter.NoGrouping = true
	amount, _ = currency.NewAmount("1245", "EUR")
	fmt.Println(formatter.Format(amount))

	formatter.MinDigits = 0
	fmt.Println(formatter.Format(amount))

	formatter.CurrencyDisplay = currency.DisplayNone
	fmt.Println(formatter.Format(amount))
}

```

Output:

```
<nil> ¥1,245.988
¥1,245.99
€1245.00
€1245
1245
```

**Comment by bojanz** [comment]
We fall back to `en` if the specified locale is not found, that's why it works.

**Comment by bojanz** [comment]
I've made two commits to improve the current behavior and ensure " " is always treated the same as "en".

https://github.com/bojanz/currency/commit/d662aacf43040d4e5703dc0770504d1fc96d8de3
https://github.com/bojanz/currency/commit/6f1903fa66a3a07941b8271a561ae1bfa230c2f1
