### ISSUE TITLE
Rework locale data filtering (-modern is going away)

### ISSUE THREAD

**Issue by bojanz** [bojanz/currency#34]
CLDR v45 deprecated the "modern" packages. Instead, we are expected to use the "full" packages and then filter locales based on the data in  https://github.com/unicode-org/cldr-json/blob/main/cldr-json/cldr-core/coverageLevels.json

Reference: https://unicode-org.atlassian.net/browse/CLDR-16465

**Comment by Ishwarya-Selvaraj** [comment]
I would like to give it a try @bojanz
