### ISSUE TITLE
Question: String value to currency and rate extraction

### ISSUE THREAD

**Issue by bentcoder** [bojanz/currency#36]
Hi,

Does this library extract and output the numeric bit for the given string representation? See dummy examples below.

Thanks

```bash
out := some.Function("HK$2,990.12")
out.Symbol() -> "HK$"
out.Digit() -> "2,999"
out.Decimal() -> "12"
```
```
sym, dig, dec := some.Function("HK$2,990.12")
```

**Comment by DuncanSmith** [comment]
Could you given an example of using the parse method for this use case please, even without the currency symbol. For example, if I have a value "0,49" EUR, passing this in to currency.NewAmount("0,49", "EUR") does not work; it's expecting "0.49". Can this be achieved by passing in localised formatting? It's what's being explained in this post https://stackoverflow.com/questions/45079074/parse-currency-float-string-to-float-type-based-on-locale-in-go

**Comment by bojanz** [comment]
There's an example in GoDoc: https://pkg.go.dev/github.com/bojanz/currency#example-Formatter.Parse

**Comment by DuncanSmith** [comment]
Ah, classic RTFM! 🤦‍♂️ Thank you.
