### ISSUE TITLE
Does MarshalJSON consider support symbols?

### ISSUE THREAD

**Issue by shuqingzai** [bojanz/currency#38]
Currently, JSON only outputs the amount and currency. When displayed on the front end, it often requires symbol support. I hope it can be supported

old

```json
{
  "number": "123.45",
  "currency": "CNY",
}
```

new

```json
{
  "amount": "123.45",
  "currencyCode": "CNY",
  "currency": {
    "symbol": "CN￥",
    symbolNarrow: "¥",
    "displayName": "人民币",
    "numericCode": "156",
    "currencyCode": "CNY",
    "defaultFractionDigits": 2
  }
}
```

**Comment by bojanz** [comment]
Hi, this would be out of scope for MarshalJSON, which aims to expose an amount as JSON in the least amount of bytes possible.

You have two options:
1) Create your own struct which will contain both the amount and the formatted amount (as generated by currency.Formatter).
2) Use [intl.NumberFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat) on the frontend to handle your formatting needs. It uses the same CLDR data as this package.
