### ISSUE TITLE
Handle minor amount values

### ISSUE THREAD

**Issue by Kunde21** [bojanz/currency#5]
Financial APIs use minor values in order to avoid any invalid amounts or ambiguous encoding.  

As this library stands, it is unable to handle parsing amounts from or writing amounts to a string in minor units.  `ToMinorUnits` risks overflow attacks on int64 datatype.

**Comment by bojanz** [comment]
Let's add a NewFromMinorUnits() which parallels ToMinorUnits(), and use strings for both.

How does that sound?

**Comment by Kunde21** [comment]
I'm experimenting with a type `currency.Minor` that embeds an amount, so the encoding/decoding can be handled properly, as well.

**Comment by bojanz** [comment]
Fixed in e18a43233c0ec25e3ad0d130e580d56d6d031158.

Followup: https://github.com/bojanz/currency/pull/11
